project:
  type: website

website:
  title: "*Pan narrans* - the story telling ape"
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RichardJActon
      - icon: mastodon
        href: https://scholar.social/@RichardJActon
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      dark: cyborg
      light: cosmo
    css: styles.css



