project:
  type: website

website:
  title: "*Pan narrans* - the story telling ape"
  site-url: "https://richardjacton.gitlab.io/pan-narrans-blog/"
  open-graph: true
  twitter-card:
    creator: "@richardjacton@scholar.social"
  comments: 
    hypothesis: true
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RichardJActon
      - icon: mastodon
        href: https://scholar.social/@RichardJActon
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      dark: cyborg
      light: [custom.scss cosmo]
    css: styles.css



